routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('/post/{id}', 'HomeController@post')->name('post');
Route::get('/page/{id}', 'HomeController@page')->name('page');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{id}', 'HomeController@category')->name('category');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
	Route::view('/', 'admin.home')->name('home');
	Route::resource('/posts', 'Admin\PostController');
	Route::resource('/categories', 'Admin\CategoryController');
	Route::resource('/pages', 'Admin\PageController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //

    protected $fillable = ['title','content','category_id','author_id'];

    public function author()
    {
        return $this->hasOne('App\User', 'id', 'author_id');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'post_category');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['posts'] = Post::orderBy('created_at', 'desc')->simplePaginate(10);
        return view('admin.posts.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = Category::get();
        return view('admin.posts.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'content' => 'required',
        ]);

        $post = Post::make($request->all());
        $post->author_id = auth()->user()->id;
        $post->save();

        // Agregamos las categorias
        $post->categories()->attach($request->categories);

        return redirect()->route('admin.posts.index')->with('success','Nuevo post #'.$post->id.' '.$post->title.' creado correctamente.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $data['categories'] = Category::get();
        $data['post'] = $post;
        return view('admin.posts.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => 'required',
            'content' => 'required',
        ]);

        $post->update($request->all());

        // Sincronizamos las categoráis
        $post->categories()->sync($request->categories);

        return redirect()->route('admin.posts.index')->with('success','Post #'.$post->id.' modificado correctamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('admin.posts.index')->with('success','Post #'.$post->id.' "'.$post->title.'" eliminado correctamente.');;
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')


@section('admin-title', 'Nuevo post')
@section('admin-content')

<form id="store-form" name="store-form" action="{{ route('admin.posts.store') }}" method="post">
  <div class="form-group">
    @csrf
    <label for="title">Título</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Título del post" required>
  </div>
  <div class="form-group">
    <label for="content">Contenido</label>
    <textarea class="form-control" id="content" name="content" rows="5" placeholder="Contenido del post" required></textarea>
  </div>
  <div class="form-group">
    <label for="categories">Categorías</label>
    <select multiple class="form-control" id="categories" name="categories[]">
      @foreach($categories as $category)
      <option value="{{$category->id}}">{{ $category->name }}</option>
      @endforeach
    </select>
  </div>
</form>
<button form="store-form" type="submit" class="btn btn-primary">Guardar</button> 
<a class="btn btn-secondary" href="{{ route('admin.posts.index') }}">Cancelar</a>

@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')


@section('admin-title')
Editando post <strong>#{{$post->id}} {{$post->title}}</strong>
@endsection

@section('admin-content')

<form id="edit-form" name="edit-form" action="{{ route('admin.posts.update', $post->id) }}" method="post">
  <div class="form-group">
    @csrf
    @method('PUT')
    <label for="title">Título</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Título del post" value="{{$post->title}}" required>
  </div>
  <div class="form-group">
    <label for="content">Contenido</label>
    <textarea class="form-control" id="content" name="content" rows="5" required>{{$post->content}}</textarea>
  </div>
  <div class="form-group">
    <label for="categories">Categorías</label>
    <select multiple class="form-control" id="categories" name="categories[]">
      @foreach($categories as $category)
      <option value="{{$category->id}}" {{ ($post->categories->contains($category)) ? 'selected' : ''}}>{{ $category->name }}</option>
      @endforeach
    </select>
  </div>
</form>
<button form="edit-form" type="submit" class="btn btn-primary">Guardar</button> 
<a class="btn btn-secondary" href="{{ route('admin.posts.index') }}">Cancelar</a>
<button form="remove-form" class="btn btn-outline-danger float-right" type="submit" onclick="return confirm('¿Desea eliminar este post?')"><i class="fa fa-remove"></i> Eliminar</button>

<form id="remove-form" name="remove-form" action="{{ route('admin.posts.destroy', $post->id)}}" method="post">
@csrf
@method('DELETE')
</form>

@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')


@section('admin-title', 'Listado de Posts')
@section('admin-content')

<p>Desde aquí podrá consultar la lista de Posts existentes además de crear, modificar y eliminar este tipo de contenido.</p>

<table class="table table-hover">
<thead class="thead-light">
<tr>
<th scope="col">#</th>
<th scope="col">Título</th>
<th scope="col">Autor</th>
<th scope="col" class="text-center">Fecha</th>
<th scope="col" class="text-center">Acción</th>
</tr>
</thead>
<tbody>
@foreach($posts as $post)
<tr>
<th scope="row">{{$post->id}}</th>
<td>{{$post->title}}</td>
<td>{{$post->author->name}}</td>
<td class="text-center"><time datetime="{{$post->updated_at}}" title="{{$post->updated_at}}">{{$post->updated_at->format('d/m/Y')}}</time></td>
<td class="text-center">
    <a href="{{ route('admin.posts.edit', $post->id) }}" title="Editar"><i class="fa fa-edit"></i></a>
</td>
</tr>
@endforeach
</tbody>
</table>
{{ $posts->links() }}

<a href="{{ route('admin.posts.create')}}" class="btn btn-primary">Nuevo</a>
@endsection