routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('/post/{id}', 'HomeController@post')->name('post');
Route::get('/page/{id}', 'HomeController@page')->name('page');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{id}', 'HomeController@category')->name('category');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
	Route::view('/', 'admin.home')->name('home');
	Route::resource('/posts', 'Admin\PostController');
	Route::resource('/categories', 'Admin\CategoryController');
	Route::resource('/pages', 'Admin\PageController');
});

resources/views/admin/pages/create.blade.php
@extends('layouts.admin')


@section('admin-title', 'Nuevo página')
@section('admin-content')

<form id="store-form" name="store-form" action="{{ route('admin.pages.store') }}" method="post">
  <div class="form-group">
    @csrf
    <label for="title">Título</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Título de la página" required>
  </div>
  <div class="form-group">
    <label for="content">Contenido</label>
    <textarea class="form-control" id="content" name="content" rows="5" placeholder="Contenido de la página" required></textarea>
  </div>
</form>
<button form="store-form" type="submit" class="btn btn-primary">Guardar</button> 
<a class="btn btn-secondary" href="{{ route('admin.pages.index') }}">Cancelar</a>

@endsection

resources/views/admin/pages/edit.blade.php
@extends('layouts.admin')


@section('admin-title')
Editando página <strong>#{{$page->id}} {{$page->title}}</strong>
@endsection

@section('admin-content')

<form id="edit-form" name="edit-form" action="{{ route('admin.pages.update', $page->id) }}" method="post">
  <div class="form-group">
    @csrf
    @method('PUT')
    <label for="title">Título</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Título de la página" value="{{$page->title}}" required>
  </div>
  <div class="form-group">
    <label for="content">Contenido</label>
    <textarea class="form-control" id="content" name="content" rows="5" required>{{$page->content}}</textarea>
  </div>
</form>
<button form="edit-form" type="submit" class="btn btn-primary">Guardar</button> 
<a class="btn btn-secondary" href="{{ route('admin.pages.index') }}">Cancelar</a>
<button form="remove-form" class="btn btn-outline-danger float-right" type="submit" onclick="return confirm('¿Desea eliminar esta página?')"><i class="fa fa-remove"></i> Eliminar</button>

<form id="remove-form" name="remove-form" action="{{ route('admin.pages.destroy', $page->id)}}" method="post">
@csrf
@method('DELETE')
</form>

@endsection

resources/views/admin/pages/index.blade.php
@extends('layouts.admin')


@section('admin-title', 'Listado de páginas')
@section('admin-content')

<p>Desde aquí podrá consultar la lista de páginas existentes además de crear, modificar y eliminar este tipo de contenido.</p>

<table class="table table-hover">
<thead class="thead-light">
<tr>
<th scope="col">#</th>
<th scope="col">Título</th>
<th scope="col">Autor</th>
<th scope="col" class="text-center">Fecha</th>
<th scope="col" class="text-center">Acción</th>
</tr>
</thead>
<tbody>
@foreach($pages as $page)
<tr>
<th scope="row">{{$page->id}}</th>
<td>{{$page->title}}</td>
<td>{{$page->author->name}}</td>
<td class="text-center"><time datetime="{{$page->updated_at}}" title="{{$page->updated_at}}">{{$page->updated_at->format('d/m/Y')}}</time></td>
<td class="text-center">
    <a href="{{ route('admin.pages.edit', $page->id) }}" title="Editar"><i class="fa fa-edit"></i></a>
</td>
</tr>
@endforeach
</tbody>
</table>
{{ $pages->links() }}

<a href="{{ route('admin.pages.create')}}" class="btn btn-primary">Nuevo</a>
@endsection