routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', 'HomeController@index')->name('home');
Route::get('/post/{id}', 'HomeController@post')->name('post');
Route::get('/page/{id}', 'HomeController@page')->name('page');
Route::get('/categories', 'HomeController@categories')->name('categories');
Route::get('/category/{id}', 'HomeController@category')->name('category');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
	Route::view('/', 'admin.home')->name('home');
	Route::resource('/posts', 'Admin\PostController');
	Route::resource('/categories', 'Admin\CategoryController');
	Route::resource('/pages', 'Admin\PageController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->belongsToMany('App\Post', 'post_category');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['categories'] = Category::get();
        return view('admin.categories.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $category = Category::create($request->all());

        return redirect()->route('admin.categories.index')->with('success','Nueva categoría #'.$category->name.' creada correctamente.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $data['category'] = $category;
        return view('admin.categories.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $category->update($request->all());
        return redirect()->route('admin.categories.index')->with('success','Categoría '.$category->name.' actualizada.');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.categories.index')->with('success','Categoría '.$category->name.' eliminada.');;
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')


@section('admin-title', 'Nueva categoría')
@section('admin-content')

<form id="store-form" name="store-form" action="{{ route('admin.categories.store') }}" method="post">
  <div class="form-group">
    @csrf
    <label for="name">Nombre</label>
    <input type="text" name="name" class="form-control" id="name" placeholder="Nombre de la categoría" required>
  </div>
</form>
<button form="store-form" type="submit" class="btn btn-primary">Guardar</button> 
<a class="btn btn-secondary" href="{{ route('admin.categories.index') }}">Cancelar</a>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')


@section('admin-title')
Editando categoría <strong>#{{$category->name}}</strong>
@endsection

@section('admin-content')

<form id="edit-form" name="edit-form" action="{{ route('admin.categories.update', $category->id) }}" method="post">
  <div class="form-group">
    @csrf
    @method('PUT')
    <label for="name">Nombre</label>
    <input type="text" name="name" class="form-control" id="name" placeholder="Nombre de la categoría" value="{{$category->name}}" required>
  </div>
</form>
<button form="edit-form" type="submit" class="btn btn-primary">Guardar</button> 
<a class="btn btn-secondary" href="{{ route('admin.categories.index') }}">Cancelar</a>
<button form="remove-form" class="btn btn-outline-danger float-right" type="submit" onclick="return confirm('¿Desea eliminar esta categoría?')"><i class="fa fa-remove"></i> Eliminar</button>

<form id="remove-form" name="remove-form" action="{{ route('admin.categories.destroy', $category->id)}}" method="post">
@csrf
@method('DELETE')
</form>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')


@section('admin-title', 'Listado de categorías')
@section('admin-content')

<p>Desde aquí podrá consultar la lista de categorías existentes.</p>

<table class="table table-hover">
<thead class="thead-light">
<tr>
<th scope="col">#</th>
<th scope="col">Nombre</th>
<th scope="col" class="text-center">Acción</th>
</tr>
</thead>
<tbody>
@foreach($categories as $category)
<tr>
<th scope="row">{{$category->id}}</th>
<td>{{$category->name}}</td>
<td class="text-center">
    <a href="{{ route('admin.categories.edit', $category->id) }}" title="Editar"><i class="fa fa-edit"></i></a>
</td>
</tr>
@endforeach
</tbody>
</table>

<a href="{{ route('admin.categories.create')}}" class="btn btn-primary">Nuevo</a>
@endsection